export const INPUT_CHANGE = 'INPUT_CHANGE';
export const RESET_REDUCER = 'RESET_REDUCER';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const MODAL_CHANGE = 'MODAL_CHANGE';
export const SAVE_CHOICE = 'SAVE_CHOICE';
export const UPDATE_CHOICE = 'UPDATE_CHOICE';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';
